- hosts: windows
  gather_facts: no
  tasks:
    - name: "Install git"
      win_chocolatey: name=git state=present

- hosts: windows
  gather_facts: no
  tasks:
    - name: "Install cmder"
      win_chocolatey: name=cmder state=present
