- hosts: windows
  gather_facts: no
  tasks:
    - name: "Install git"
      win_chocolatey: name=git state=present

    - name: Install python
      win_chocolatey: name=python3 state=present

- hosts: windows
  tasks:
    - name: Uninstall capture service
      win_package:
        path: C:\wk\ScanService.19.0.24.msi
        state: absent
        arguments: /quiet /norestart

    - name: Install capture service
      win_package:
        path: C:\wk\ScanService.19.0.24.msi
        state: present
        arguments: /quiet /norestart

    - name: Copy appsettings.json
      win_copy:
        src: resource/appsettings.json
        dest: C:\Program Files (x86)\BCircle\ScanService\appsettings.json

    - name: Restart a service
      win_service:
        name: "B Circle ScanService.19.0.24"
        state: restarted
