- hosts: windows
  gather_facts: no
  tasks:
    - name: Install procmon
      win_chocolatey: name=procmon  status=present

- hosts: windows
  gather_facts: no
  tasks:
    - name: Install procexp
      win_chocolatey: name=procexp  status=present
