- hosts: windows
  gather_facts: no
  tasks:
    - name: "Install git"
      win_chocolatey: name=git state=present

    - name: Install python
      win_chocolatey: name=python3 state=present

    # - name: Install an MSI file
    #   win_msi:
    #     path: /wk/ScanService.19.0.24.msi
    #     wait: yes

- hosts: windows
  tasks:
    - name: Uninstall capture service
      win_package:
        path: C:\wk\ScanService.19.0.24.msi
        state: absent
        arguments: /quiet /norestart

    - name: Install capture service
      win_package:
        path: C:\wk\ScanService.19.0.24.msi
        state: present
        arguments: /quiet /norestart
